version: '3.8'

services:
  mcp:
    build: .
    volumes:
      - ./data/docusaurus:/app/docs/build            # Built Docusaurus site (served by FastAPI if needed)
      - ./data/embeddings:/app/embeddings            # Embedding storage
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=vector_db
    ports:
      - "8000:8000"                                  # FastAPI MCP service

  docusaurus-dev:
    image: node:18
    working_dir: /app/docs
    volumes:
      - ./app/docs:/app/docs                         # Full Docusaurus source project
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector_db
    volumes:
      - pgdata:/var/lib/postgresql/data

# TODO add proxy sse server + port redirect
volumes:
  pgdata:
