version: '3.8'

services:
  mcp:
    build: .
    volumes:
      - ./data/docusaurus:/app/docs             # Docusaurus content managed by MCP
      - ./data/embeddings:/app/embeddings       # Embedding storage
      - ./doc:/app/doc                          # Full Docusaurus project
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=vector_db
    ports:
      - "8000:8000"                             # FastAPI MCP service

  docusaurus-dev:
    image: node:18
    working_dir: /app/doc
    volumes:
      - ./doc:/app/doc
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: